# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa4350793707c3cd3e9b60c66ab5b8f3717556035eec910e995f23f06b3562f3f189a9eb6a6040bf57a437d3ec8607a72d2ddd3d6b0a04ebd91139bef393ec8a

test:
  secret_key_base: a8648bbe9745b8795594af1eaed97312f101196459d7b223a0549c0652a63b938886ade0e71229412b1c8b18e7941f8c773fe4e0fd21d5d000f4bd83f3d0c2f0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
